baseurl:
title: convergeML
subtitle:
author: shoaibkhanz
simple_search: http://google.com/search
description: converge to better learning
name:
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
page:
  template: _page.txt
  extension: md
post:
  template: _post.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination:

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-shoaibkhanz-github-io-convergeml

    # Google services
google_analytics: UA-166788498-1